### PR TITLE
Update snapcraft.yaml

### PR DESCRIPTION
**Pull request by popey**
Enable application to work on xwayland

### CODE REVIEW

**Review by dbrgn — APPROVED** [review]

**Comment by dbrgn** [comment]
@ubruhin do you know how complicated it would be to add wayland support? https://wiki.qt.io/QtWayland

**Comment by popey** [comment]
Well, it may actually just be a case of staging `libwayland-dev` as a build package and stage the relavent libwayland client package. Might actually "just work". Worth testing instead of this PR.

**Comment by rnestler** [comment]
> Worth testing instead of this PR.

Could you test this @popey?

**Comment by ubruhin** [comment]
Oops I forgot that this PR is still open :sob:

I now tried to get it running with wayland support - basically the application seems to work well, but the window decoration theme is very different to the rest of the OS, which looks very ugly. This problem doesn't exist with xwayland. I also checked `snapcraft.yml` of various other Qt applications - I didn't found one which does *not* disable wayland :see_no_evil: 

Thus I have now applied this patch (with small differences) on the master branch so this PR can be closed. Thanks anyway!

**Pull request closed without merging**
